### ISSUE TITLE
例子中的聊天，怎么手动下线？

### ISSUE THREAD

**Issue by xybin1990** [node-pinus/pinus#105]
功能需要是手动连接，然后聊天结束手动下线？怎样调用下线的功能？

**Comment by xybin1990** [comment]
知道了，pomelo.disconnect()

**Comment by whtiehack** [comment]
这是断开与服务器的连接。

**Comment by xybin1990** [comment]
> 这是断开与服务器的连接。

断开就算是下线了是吧？还有其他方式吗？

**Comment by xybin1990** [comment]
@whtiehack 断开就算是下线了是吧？还有其他方式吗？

**Comment by whtiehack** [comment]
还有服务器主动踢掉？。。

**Comment by xybin1990** [comment]
额，不用服务器主动踢掉，前端页面上手动下线。就这样应该就可以了。
