### ISSUE TITLE
怎么获取当前状态

### ISSUE THREAD

**Issue by xybin1990** [node-pinus/pinus#106]
前端怎样判断当前状态？如果掉线了，重连没有连上，怎么来获取当前连接状态，需要显示出来这个状态

**Comment by whtiehack** [comment]
pomelo对象有状态字段。找一下

**Comment by xybin1990** [comment]
@whtiehack 还是没找到怎么获取这个状态

**Comment by whtiehack** [comment]
看了一下。没状态，只能 事件。  监听事件就好了 
```js
pomelo.on('close',()=>{})
```

**Comment by xybin1990** [comment]
@whtiehack 这个貌似不能监控到自己掉线了吧？事件是针对其他成员的？我在chatHandler中新增了一个getUser的方法，来获取rid中成员，但是这个也是主动获取，不能作为在线状态的判断吧

**Comment by whtiehack** [comment]
没明白你要问啥。你到底是要问前端的还是后端的。

**Comment by xybin1990** [comment]
@whtiehack 前端，想有一个状态，这样可以知道自己当前是否在线或者离线。事件只是可以看到是否有新的人员加入或者离开。

**Comment by whtiehack** [comment]
```js
let isonline = false
pomelo.init({},()=>{isonline = true})
pomelo.on('close',()=>{isonline = false})  
```

**Comment by xybin1990** [comment]
@whtiehack 👌
