### ISSUE TITLE
pinus/lib/connectors/commands/handshake.ts 类型定义有误

### ISSUE THREAD

**Issue by DeloDuan** [node-pinus/pinus#11]
export interface HandshakeCommandOptions {
    handshake ?: HanshakeFunction;
    heartbeat ?: number;
    checkClient ?: CheckClientFunction;
    useDict ?: boolean;
    useProtobuf ?: boolean;
    useCrypto ?: boolean;
}

**Comment by DeloDuan** [comment]
export type CheckClientFunction = (type:any, version:any) => boolean;

**Comment by DeloDuan** [comment]
之前 checkClient类型 是boolean 型

**Comment by mybios** [comment]
感谢提问题。
已修复。
