### ISSUE TITLE
官网新手教程->启动web-server服务器->node app后报错

### ISSUE THREAD

**Issue by PotentialSteffan** [node-pinus/pinus#113]
app.configure(function(){
    ^

TypeError: app.configure is not a function

**Comment by PotentialSteffan** [comment]
是express版本的问题，现在默认安装的是4.x版本，不兼容3.x的api

**Comment by whtiehack** [comment]
好  周一有空的话我去修复一下。

**Comment by whtiehack** [comment]
4.0的话正确的应该是哪样的？

**Comment by PotentialSteffan** [comment]
我这边手动把express降到3.x版本可以正常运行。如果要升级4.x就要去看express的文档作相应的修改了；如果不升级不知道能不能在依赖里面将express固定写成3.x版本；这样新手就不会按照教程走跑不起来了。

**Comment by yilinershi** [comment]
截止20210904，该问题依然存在，今天试着跑demo直接跑不动，按上面兄弟说的，express改成3.x版本就ok了
