### ISSUE TITLE
处理http请求

### ISSUE THREAD

**Issue by yunmin97** [node-pinus/pinus#114]
如何添加一个http服务器并且能够和其他服务器进行交互（如：http服务器收到请求后，http能够再通通知其他任何一个服务器）？
或者是直接处理http请求？

**Comment by whtiehack** [comment]
pinus进程也是一个nodejs进程啊。可以配置一个http服务器类型，然后你就用nodejs的正常方法 起一个 http服务。然后来请求的时候用rpc 通知其它服务器。
