### ISSUE TITLE
web-server 最新的express 中 configure 接口已经被移除了

### ISSUE THREAD

**Issue by wetiontop** [node-pinus/pinus#116]
TypeError: app.configure is not a function

**Comment by whtiehack** [comment]
这个已经修复了。只是还没发布版本。。

**Comment by wetiontop** [comment]
好的，有计划什么时候发布吗？

**Comment by whtiehack** [comment]
你可以先手动改一下。  只是个小bug。。 没有什么影响的东西 。 打算等下次更新的时候一起发布。
https://github.com/node-pinus/pinus/blob/master/examples/websocket-chat/web-server/app.js

**Comment by wetiontop** [comment]
你这个修改我之前改过，但是会有其他的问题比如express.methodOverride(),说这些模块已经脱离express了，要另外引入才行。我已经把express恢复到老的版本了，先这样用着先。
