### ISSUE TITLE
pinus init 是否有加入js模版的计划

### ISSUE THREAD

**Issue by wetiontop** [node-pinus/pinus#117]
由于想用js写业务逻辑，pinus是否有创建js版的工程计划？

**Comment by whtiehack** [comment]
没有。 你可以使用隔壁的 pomelo。

**Comment by wetiontop** [comment]
算了，隔壁的感觉没人维护了

**Comment by whtiehack** [comment]
你可以不用 TS的模板。
直接用js码代码。 
因为库发出以后本来就是js的。
包括自己的项目，TS编译完就是js。
