### ISSUE TITLE
按照教程编译game-server报错 找不到namespace SOCKET.IO

### ISSUE THREAD

**Issue by niguifu** [node-pinus/pinus#12]
pinus/lib/sioconnector.ts  和 pinus/lib/siosocket.ts 中！ 
把 SOCKET.IO 类型 改成any就可以编译了。

**Comment by whtiehack** [comment]
https://github.com/nestjs/nest/issues/512#issuecomment-373766807

**Comment by WangPengJu** [comment]
`npm install @types/socket.io@1.4.31 --save`
