### ISSUE TITLE
readme里 demo链接已失效

### ISSUE THREAD

**Issue by donhwa** [node-pinus/pinus#127]
此链接已404
https://github.com/NetEase/pinus/wiki/Introduction-to--Lord-of-Pinus

**Comment by whtiehack** [comment]
https://github.com/NetEase/pomelo/wiki/Introduction-to--Lord-of-Pomelo

**Comment by donhwa** [comment]
pomelo的链接我了解的，pinus的readme不准备订正吗？

**Comment by whtiehack** [comment]
你说的是wiki吗？  我个人是没有时间去改的。如果你有兴趣做贡献你可以直接改的。谢谢。
