### ISSUE TITLE
是否考虑把 types-mqtt-connection 发布到 npm 上？ 

### ISSUE THREAD

**Issue by bruce48x** [node-pinus/pinus#128]
安装时经常因为网络问题（types-mqtt-connection 用得是 github url）安装失败，
还是发到 npm 比较稳定

**Comment by whtiehack** [comment]
的确会受到github网络的影响. 有时间我研究研究下这个问题,看怎么处理.

**Comment by bruce48x** [comment]
> 的确会受到github网络的影响. 有时间我研究研究下这个问题,看怎么处理.

一个变通的做法是改 pakcage.json，把这个移到 devDependencies，
包括 @types/mocha 哪些都没必要放在 dependencies

**Comment by whtiehack** [comment]
> > 的确会受到github网络的影响. 有时间我研究研究下这个问题,看怎么处理.
> 
> 一个变通的做法是改 pakcage.json，把这个移到 devDependencies，
> 包括 @types/mocha 哪些都没必要放在 dependencies


不错的想法.我改一下

**Comment by whtiehack** [comment]
1.4.8已经解决这个问题了.
