### ISSUE TITLE
新建项目编译出错

### ISSUE THREAD

**Issue by bruce-yan** [node-pinus/pinus#129]
![1](https://user-images.githubusercontent.com/24974326/82279407-134f7880-99bf-11ea-8762-6bacadebf9e2.png)

**Comment by whtiehack** [comment]
没见过你这种问题. 环境是什么,版本是什么,新项目选的协议是什么.

**Comment by bruce-yan** [comment]
> 没见过你这种问题. 环境是什么,版本是什么,新项目选的协议是什么.

我windows,mac都试了
windows环境: win10, nodejs-12.16.3LTS, pinus1.4.4
mac环境: mac10.15.4, nodejs-8.9.3LTS, pinus1.4.4

这个例子不出错　git clone https://github.com/LinDejiang/pinus-chat-example.git
但新建项目编译出错
![2](https://user-images.githubusercontent.com/24974326/82280613-d33dc500-99c1-11ea-8e83-d971d7c609be.png)

**Comment by bruce-yan** [comment]
协议选的是1

**Comment by whtiehack** [comment]
复现了,我查一下.

**Comment by whtiehack** [comment]
给你自己的 `tsconfig.json` 加一个 skipLibCheck

![image](https://user-images.githubusercontent.com/12741016/82303146-237e4c80-99ed-11ea-99f0-7c33c3350c8a.png)

等会修复一下这个问题

**Comment by daqiuqu** [comment]
pinus 1.4.8 确定已解决
