### ISSUE TITLE
发现channel.pushMessage的效率并不高，千人在线聊天的情况下会很卡

### ISSUE THREAD

**Issue by linguitang** [node-pinus/pinus#130]

**Comment by whtiehack** [comment]
在什么样的环境下,怎么测试的呀

**Comment by linguitang** [comment]
应该是我自己的问题，出现了这个错误，然后就心跳超时了，我是在用框架的机器人做压力测试的时候出现的
![image](https://user-images.githubusercontent.com/8371546/83607717-49d7e680-a5ae-11ea-98bc-b88884eec19b.png)

**Comment by linguitang** [comment]
暂时看是因为带宽不足，阻塞导致的

**Comment by linguitang** [comment]
把服务器调成按流量计费，最大带宽200M了一样会有问题，只要注释掉pushMessage就不会卡顿，一调用就卡顿，先把问题给重开了，我去看pushMessage源码，找到问题再来回复

**Comment by linguitang** [comment]
对了，我是ts直接运行的

**Comment by linguitang** [comment]
可能跟这个有关系，我是pm2 启动的

**Comment by whtiehack** [comment]
一般pm2 疯掉都是日志疯掉了. 尝试关一下日志试试

**Comment by linguitang** [comment]
日志关闭了还是一样的问题

**Comment by whtiehack** [comment]
那就先别用pm2启动.直接启动 试试

**Comment by linguitang** [comment]
试了直接启动也是一样，remoteConfig里面设置了bufferMsg后，效果好了不少，但是依旧是卡，然后就一大堆的机器人心跳超时，就掉线了

**Comment by whtiehack** [comment]
虽然你没描述清楚,但是我好像猜到你是怎么测试的了

你这1000个是在不停的全服推送消息吧?

c1 c2 c3 --- c1000

任何一个客户端发送一个消息,都要推送给1000个其它人. 这样的逻辑对服务器的负担是很重的.

消息量是指数级增长的. 1人发送一次就是1000次消息推送,  10人同时发送一次就是1万次消息推送. 

你加的 `bufferMsg`  也是一种缓解的方法,如果你的业务对实时要求不高.可以再加大这个值.

另外这种情况下用 broadcast方法的话性能能稍微好一点
如果是分组的.那么需要用 用分组的broadcast. 


实际开发中是要避免这样的情况的.如果一定要有这种需求,就需要增加大量的connector,还需要做分批处理. 让消息慢慢发送.具体实现可以编写自定义的 scheduler(需要实现`IPushScheduler`),然后配置到 `pushSchedulerConfig` 参数里.

不然connector全在处理推送消息了,cpu直接占满了.没办法处理其它逻辑了. 所以当然就心跳超时了.

**Comment by linguitang** [comment]
是的,我就是模拟全服1000人在线聊天，每人随机时间间隔（1-10秒）内发一句话，发送的消息是所有人都要接收

**Comment by linguitang** [comment]
我原本聊天的话想的是按channel分配，全服一个频道，帮派一个频道。broadcast 和channel.pushMessage的性能应该差距不大吧

**Comment by whtiehack** [comment]
> broadcast 和channel.pushMessage的性能应该差距不大吧

是的.不大

**Comment by linguitang** [comment]
现在就是根据需求对发送消息进行优化，像聊天之类的这种消息可以先缓存起来，一秒钟发送一次就行了。其他的情况，在保证功能实现的情况下，尽可能地降低消息发送频率

**Comment by linguitang** [comment]
等修改完之后，我再测试一遍，再来这边反馈

**Comment by whtiehack** [comment]
指数级发送消息肯定是不行的,肯定要分布开的.不然什么服务器都抗不住.这就是为什么 那些消息推送平台都是分布式的原因吧.

**Comment by linguitang** [comment]
最终结果，调整了最大带宽200M，日志级别调成warn以上，对消息进行整理缓存，没必要实时的消息一秒钟统一发送一次，现在服务器表现良好，感谢！
