### ISSUE TITLE
error TS2688: Cannot find type definition file for 'node'.

### ISSUE THREAD

**Issue by gmajrtfp** [node-pinus/pinus#14]
<img src="http://gmajrtfp.oss-cn-shenzhen.aliyuncs.com/download/微信截图_20180323195920.png">

**Comment by WangPengJu** [comment]
npm install typescript -g

**Comment by WangPengJu** [comment]
npm install @types/node --save

**Comment by gmajrtfp** [comment]
<img src="http://gmajrtfp.oss-cn-shenzhen.aliyuncs.com/download/微信截图_20180324201913.png">

还是会报错

**Comment by whtiehack** [comment]
n这是socketio库有问题 #12
