### ISSUE TITLE
运行 npm run build 报错

### ISSUE THREAD

**Issue by BugIsFriend** [node-pinus/pinus#140]
error TS2345: Argument of type 'Server' is not assignable to parameter of type 'string | number'.
  Type 'Server' is not assignable to type 'number'.

139         let sio = socket_io(httpServer, opts);

**Comment by whtiehack** [comment]
pinus版本是啥?是用pinus命令行生成的项目吗?

**Comment by BugIsFriend** [comment]
恩是的 ！

**Comment by whtiehack** [comment]
没看懂呀.能提供详细一点的信息吗?

或者把复现步骤描述一下.
