### ISSUE TITLE
MMO Demo 不见啦！

### ISSUE THREAD

**Issue by RedKeys** [node-pinus/pinus#144]
没有 DEMO 门槛就高啦，不能快速研究上手啊。
![image](https://user-images.githubusercontent.com/35087454/100721382-393be800-33fa-11eb-9cb7-bcbe4e6c1028.png)

**Comment by RedKeys** [comment]
LordOfPinus 安装指南

git clone https://github.com/node-pinus/lordofpinus.git

**Comment by whtiehack** [comment]
https://github.com/NetEase/lordofpomelo

没有pinus的 只有pomelo的
