### ISSUE TITLE
安装pinus出错

### ISSUE THREAD

**Issue by zjl410091917** [node-pinus/pinus#15]
#：npn i -d -g pinus

npm info it worked if it ends with ok
npm info using npm@5.6.0
npm info using node@v8.9.4
npm http fetch GET 304 https://registry.npm.taobao.org/pinus 217ms (from cache)
npm http fetch GET 304 https://registry.npm.taobao.org/@types%2fmocha 85ms (from cache)
npm http fetch GET 304 https://registry.npm.taobao.org/node-bignumber 62ms (from cache)
npm http fetch GET 304 https://registry.npm.taobao.org/mkdirp 187ms (from cache)
npm http fetch GET 304 https://registry.npm.taobao.org/cliff 189ms (from cache)
npm http fetch GET 304 https://registry.npm.taobao.org/@types%2fsocket.io 191ms (from cache)
npm http fetch GET 304 https://registry.npm.taobao.org/commander 195ms (from cache)
npm http fetch GET 304 https://registry.npm.taobao.org/eyes 202ms (from cache)
npm http fetch GET 304 https://registry.npm.taobao.org/mqtt-connection 201ms (from cache)
npm http fetch GET 304 https://registry.npm.taobao.org/crc 206ms (from cache)
npm http fetch GET 304 https://registry.npm.taobao.org/pinus-admin 71ms (from cache)
npm http fetch GET 304 https://registry.npm.taobao.org/pinus-loader 68ms (from cache)
npm http fetch GET 304 https://registry.npm.taobao.org/pinus-logger 71ms (from cache)
npm http fetch GET 304 https://registry.npm.taobao.org/pinus-protocol 66ms (from cache)
npm http fetch GET 304 https://registry.npm.taobao.org/pinus-protobuf 73ms (from cache)
npm http fetch GET 304 https://registry.npm.taobao.org/pinus-rpc 69ms (from cache)
npm http fetch GET 304 https://registry.npm.taobao.org/async 277ms (from cache)
npm http fetch GET 304 https://registry.npm.taobao.org/pinus-scheduler 73ms (from cache)
npm http fetch GET 304 https://registry.npm.taobao.org/seq-queue 76ms (from cache)
npm http fetch GET 304 https://registry.npm.taobao.org/socket.io 71ms (from cache)
npm http fetch GET 304 https://registry.npm.taobao.org/ws 58ms (from cache)
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git clone -q https://github.com/node-pinus/types-mqtt-connection.git /root/.npm/_cacache/tmp/git-clone-dd44d631
npm ERR! fatal:不能为'/root/.npm/_cacache/tmp/git-clone-dd44d631' :创建先导目录：权限不够
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-03-28T11_36_25_568Z-debug.log

**Comment by zjl410091917** [comment]
使用的是root角色

**Comment by whtiehack** [comment]
`sudo npm install -g pinus`

or

`npm install -g pinus --unsafe-perm`

**Comment by zjl410091917** [comment]
@whtiehack 同样的错误

**Comment by whtiehack** [comment]
你可能要重装一下node.js ， 你可以先试试这个库 npm install -g node-gyp    或者 npm install -g pm2 看能不能装上，你这个问题不像是 pinus的问题。

**Comment by zjl410091917** [comment]
sh-3.2# npm i -d -g pinus --unsafe-perm
npm info it worked if it ends with ok
npm info using npm@5.6.0
npm info using node@v8.9.4
npm http fetch GET 304 https://registry.npm.taobao.org/pinus 356ms (from cache)
npm http fetch GET 304 https://registry.npm.taobao.org/@types%2fmocha 127ms (from cache)
npm http fetch GET 304 https://registry.npm.taobao.org/node-bignumber 60ms (from cache)
npm http fetch GET 304 https://registry.npm.taobao.org/cliff 293ms (from cache)
npm http fetch GET 304 https://registry.npm.taobao.org/mqtt-connection 291ms (from cache)
npm http fetch GET 304 https://registry.npm.taobao.org/mkdirp 293ms (from cache)
npm http fetch GET 304 https://registry.npm.taobao.org/@types%2fsocket.io 297ms (from cache)
npm http fetch GET 304 https://registry.npm.taobao.org/eyes 296ms (from cache)
npm http fetch GET 304 https://registry.npm.taobao.org/crc 298ms (from cache)
npm http fetch GET 304 https://registry.npm.taobao.org/async 300ms (from cache)
npm http fetch GET 304 https://registry.npm.taobao.org/commander 302ms (from cache)
npm http fetch GET 304 https://registry.npm.taobao.org/pinus-admin 144ms (from cache)
npm http fetch GET 304 https://registry.npm.taobao.org/pinus-loader 73ms (from cache)
npm http fetch GET 304 https://registry.npm.taobao.org/pinus-logger 87ms (from cache)
npm http fetch GET 304 https://registry.npm.taobao.org/pinus-protocol 104ms (from cache)
npm http fetch GET 304 https://registry.npm.taobao.org/pinus-protobuf 113ms (from cache)
npm http fetch GET 304 https://registry.npm.taobao.org/pinus-rpc 114ms (from cache)
npm http fetch GET 304 https://registry.npm.taobao.org/pinus-scheduler 119ms (from cache)
npm http fetch GET 304 https://registry.npm.taobao.org/seq-queue 118ms (from cache)
npm http fetch GET 304 https://registry.npm.taobao.org/socket.io 118ms (from cache)
npm http fetch GET 304 https://registry.npm.taobao.org/ws 96ms (from cache)
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git clone -q https://github.com/node-pinus/types-mqtt-connection.git /var/root/.npm/_cacache/tmp/git-clone-af01964a
npm ERR! fatal: could not create leading directories of '/var/root/.npm/_cacache/tmp/git-clone-af01964a': Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/root/.npm/_logs/2018-03-31T04_03_06_476Z-debug.log



@whtiehack 我在MAC上安装同样的错误  node-gyp等安装是没有问题的

**Comment by whtiehack** [comment]
别加 -d 试试。。

**Comment by mybios** [comment]
权限问题要先执行sudo -s切换到root用户，再执行安装

**Comment by yuu2lee4** [comment]
文件夹权限问题。。

**Comment by JasonAtGitHub** [comment]
一样的问题，root用户在Mac和Linux安装失败，在Windows上就没问题

**Comment by JasonAtGitHub** [comment]
Mac解决方案：将/usr/local/lib/node_modules的用户修改为当前用户，即sudo chown -R /usr/local/lib/node_modules <CurrentUser>
调用命令：npn i pinus -g
注意，不用加上sudo
