### ISSUE TITLE
关于pomelo-protocol的问题

### ISSUE THREAD

**Issue by theks** [node-pinus/pinus#150]
最近打算给某单机游戏做一个联网的mod，官方只提供了lua的接口。我想用pinus做服务器端，研究过pinus的例子之后发现pomelo/pinus底层用到了pomelo-protocol，包括客户端也是。
所以能不能提供一个lua使用pomelo-protocol或者其他与pinus通信的办法，或者简单粗暴点，在服务器端不用pomelo-protocol和各种压缩，虽然我也知道这是pomelo/pinus的优势

**Comment by whtiehack** [comment]
可以不用的啊. 你去实现个简单的 IConnector  ISocket 就好了. 怎么简单怎么来.不复杂

**Comment by theks** [comment]
@whtiehack 新年好，感谢回复。
我一开始以为只是把json变成了binary，看了一下HybridSocket，发现它还定义了package格式，就是说我得定义好自己的包格式才能在客户端用lua以相同格式的包与服务端通信。

**Comment by theks** [comment]
我在尝试写一个Lua版的pomelo-protocol.js，因为我最熟悉的语言是c#，nodejs和java有点了解，Lua完全是新手，踩了不少坑之后发现lua在处理字符串转字节数组挺方便的，比如Protocol.strencode方法，在lua里只需要string.byte(str, 1, #str)一句代码就搞定了。
另外我发现了一件事情，就是pomelo-protocol.js在处理utf8mb4字符（比如emoji表情）的时候会有问题，因为它是占4字节的，但神奇的是，我发现strencode之后，再strdecode回来居然是正确的。不知道实际使用中会不会有问题，反正在处理utf8mb4的时候Protocol.strencode方法和lua的string.byte()方法得到的结果是不一致的

**Comment by linjinxing1987** [comment]
我一直以为node.js会是以后的发展趋势，为何反过来用lua写？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "theks"<notifications@github.com&gt;; 
发送时间: 2021年1月3日(星期天) 下午4:02
收件人: "node-pinus/pinus"<pinus@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: Re: [node-pinus/pinus] 关于pomelo-protocol的问题 (#150)





 
我在尝试写一个Lua版的pomelo-protocol.js，因为我最熟悉的语言是c#，nodejs和java有点了解，Lua完全是新手，踩了不少坑之后发现lua在处理字符串转字节数组挺方便的，比如Protocol.strencode方法，在lua里只需要string.byte(str, 1, #str)一句代码就搞定了。
 另外我发现了一件事情，就是pomelo-protocol.js在处理utf8mb4字符（比如emoji表情）的时候会有问题，因为它是占4字节的，但神奇的是，我发现strencode之后，再strdecode回来居然是正确的。不知道实际使用中会不会有问题，反正在处理utf8mb4的时候Protocol.strencode方法和lua的string.byte()方法得到的结果是不一致的
 
&mdash;

**Comment by theks** [comment]
@linjinxing1987 在主帖里说了啊，那个单机游戏只提供了lua的mod接口。我只是用Lua写客户端，服务器端是pinus。
要说node.js是以后的发展趋势，这个倒不一定，没见这两年node的热度也有所下降吗。node.js的特点也决定它有局限性的，它只适合实时、高并发的场景。

**Comment by whtiehack** [comment]
@theks   https://github.com/search?q=pomelo+lua

可以参考一下别人的实现

**Comment by theks** [comment]
@whtiehack 啊，早点提醒我就好了，昨天我已经照着js把lua版的Protocol、Package、Message的encode、decode自己实现了，虽然只简单测试了一下，输入同样的参数能得到同样结果，但我觉得中间可能有问题，因为Lua这语言我不熟悉，例如不能定义固定长度的数组、判断0为true等等。搜索结果里 https://github.com/luoxinliang/pomelo_quick_x 这个项目不错，跟我的想法一样照着js版写个lua的客户端，我可以直接拿来用。其他项目基于libpomelo的我还没仔细看，没搞懂纯lua客户端怎么调用。
另外，我已经用chat示例试过了，utf8mb4字符确实是有问题的，emoji表情😘😂😍显示出的是乱码。不考虑兼容一下吗？

**Comment by whtiehack** [comment]
emoji 是 poemlo遗留问题..暂时项目上没有遇到问题 所以就没搞.  有大佬说 自己做一下编码再传给encode.
