### ISSUE TITLE
缺少packages/pinus-rpc/lib/util/proxy.ts

### ISSUE THREAD

**Issue by fuyifan** [node-pinus/pinus#16]
这个文件是不是没有上传啊

**Comment by whtiehack** [comment]
源码里都没有这个文件呀。。

**Comment by fuyifan** [comment]
因为我看到 pinus-rpc\dist\lib\util下面有proxy.js但是找不到对应的ts文件. 或许之前有并且编译过, 后来ts文件删了, 但是之前生成的.js文件没有删除

**Comment by whtiehack** [comment]
嗯。有可以以前有这个文件，但是现在不用就删掉了
