### ISSUE TITLE
isHttp 实现错误

### ISSUE THREAD

**Issue by gocpplua** [node-pinus/pinus#175]
`let isHttp = function (data: Buffer) {
    let head = data.toString('utf8', 0, 4);

    for (let i = 0, l = HTTP_METHODS.length; i < l; i++) {
        if (head.indexOf(HTTP_METHODS[i]) === 0) {
            return true;
        }
    }

    return false;
};`

`var HTTP_METHODS = [
  'GET', 'POST', 'DELETE', 'PUT', 'HEAD'
];`

如果我上传的是:DELETE,那么isHttp返回false,实际按住逻辑应该是true

**Comment by whtiehack** [comment]
`:DELETE` ?
没太看懂 为什么会有个 ":"

**Comment by gocpplua** [comment]
> `:DELETE` ?
> 没太看懂 为什么会有个 ":"

从http的方法看，可能会是'DELETE'，那么此时用head只是截取前面四个字节，就会有问题

**Comment by whtiehack** [comment]
明白了..你可以提交个pr 修复一下

**Comment by mybios** [comment]
#198 fixed
