### ISSUE TITLE
在linux类型系统上没有打开tcp端口

### ISSUE THREAD

**Issue by cn-qiuhong** [node-pinus/pinus#178]
我在centos和ubuntu及windows上都测试过，用的是官方提供的初始化示例代码：pinus init ./HelloWorld，在windows上成功开启了tcp端口，局域网内的其他设备可以访问，在centos和ubuntu上都只会开启tcp6端口，只能本机访问，请问要如何解决。
完整的测试命令如下：
pinus init ./HelloWorld
cd HelloWorld
cd game-server
npm i -d
npm run build 
cd dist 
pinus start

**Comment by whtiehack** [comment]
"tcp6端口" 是啥?..   你的linux机器是不是防火墙啊  端口确定打开了吗

**Comment by cn-qiuhong** [comment]
> "tcp6端口" 是啥?.. 你的linux机器是不是防火墙啊 端口确定打开了吗

端口是打开的，之前能运行，能连，但是上周6服务器宕机了，之后就出现这种情况了，我尝试了升级pinus，原来用的1.3.10，现在用的1.4.11，尝试了使用pomelo，无论是初始化的项目还是我的项目，启动后都只能本机连接，局域网内都访问不了。
看来我还是得自己研究了，感谢你的回复！

**Comment by cn-qiuhong** [comment]
> "tcp6端口" 是啥?.. 你的linux机器是不是防火墙啊 端口确定打开了吗

端口是打开的，之前能运行，能连，但是上周6服务器宕机了，之后就出现这种情况了，我尝试了升级pinus，原来用的1.3.10，现在用的1.4.11，尝试了使用pomelo，无论是初始化的项目还是我的项目，启动后都只能本机连接，局域网内都访问不了。
看来我还是得自己研究了，感谢你的回复！

**Comment by panminghua** [comment]
这很明显是防火墙的问题，先 telnet 一下是不是通的。

**Comment by cn-qiuhong** [comment]
> 这很明显是防火墙的问题，先 telnet 一下是不是通的。

telnet 127.0.0.1 是通的，telnet 公网ip不通

**Comment by cn-qiuhong** [comment]
> 这很明显是防火墙的问题，先 telnet 一下是不是通的。

另外firewalld是没开启的（inactive状态）

**Comment by whtiehack** [comment]
是云服务器?  云服务器要去网页后台配置端口策略

**Comment by cn-qiuhong** [comment]
> 是云服务器? 云服务器要去网页后台配置端口策略

是阿里云服务器，网页后台端口策略那里我是设置为允许所有端口的

**Comment by cn-qiuhong** [comment]
最后的解决办法：初始化云盘（相当于重装系统），然后测试了pomelo，可以连，虽然也是一样只开了tcp6端口，所以应该是系统的问题。
