### ISSUE TITLE
初看和Pomelo很相似

### ISSUE THREAD

**Issue by 2497506964** [node-pinus/pinus#21]
初看和Pomelo很相似，不知道比Pomelo好在哪  ？  消息通讯这一块是否有改进  ？  RPC还是用的Pomelo那一套吗  ？

**Comment by whtiehack** [comment]
（原型基于pomelo） 协议与pomelo一样的 只是 TS版的 Pomelo， 细节有点变化

**Comment by makilyang** [comment]
能热更新不？
