### ISSUE TITLE
"pinus": "^1.5.0", "pinus-base-plugin": "^1.5.0", 没发布这版本号呀

### ISSUE THREAD

**Issue by yp199618** [node-pinus/pinus#282]
"pinus": "^1.5.0", 
"pinus-base-plugin": "^1.5.0",
 npm仓库没发布这版本号呀

**Comment by whtiehack** [comment]
没发布这个版本吧

**Comment by yp199618** [comment]
是的,但是代码中的确用到了这个版本

**Comment by yuhj86** [comment]
@whtiehack 我看项目基本就是你在维护，那请问是什么原因一直不发不到npm上？

**Comment by whtiehack** [comment]
没有这个版本号. 我重新发布一下看看

**Comment by whtiehack** [comment]
太菜了.操作失误 变成 1.6.0了..就这样吧..太菜
