### ISSUE TITLE
为什么配置会放在dist目录下呢，有点不能理解。

### ISSUE THREAD

**Issue by Manjiz** [node-pinus/pinus#30]
RT

**Comment by whtiehack** [comment]
这是因为 typescript不能编译 json文件。也不能自动copy  json文件到dist目录。所以就这样了。
我的解决方案是  config文件全部用 ts。 可以参考下我的PR。
#26

**Comment by Manjiz** [comment]
@whtiehack 好的，这项目是不是停更了

**Comment by whtiehack** [comment]
@Manjiz 没有停更。有框架问题提交issue。 作者会来修复并发布的。

**Comment by didoupeanut** [comment]
@Manjiz 
最新提交已经处理了config配置文件的打包问题，个人看法还是维持原来的结构更简洁明了，app.ts中也不需要做更多的侵入式修改。
