### ISSUE TITLE
示例找不到

### ISSUE THREAD

**Issue by yasuoganliang** [node-pinus/pinus#32]
yujinsheng@yuezhi:~/tmp$ git clone https://github.com/node-pinus/chatofpinus-websocket.git
正克隆到 'chatofpinus-websocket'...
Username for 'https://github.com': yasuoganliang
Password for 'https://yasuoganliang@github.com': 
remote: Repository not found.
fatal: repository 'https://github.com/node-pinus/chatofpinus-websocket.git/' not found

**Comment by whtiehack** [comment]
没有这个示例，直接看源码里的　examples里的示例吧。　　pomelo与pinus只是语言上的差别，　　可以直接看pomelo的示例.
