### ISSUE TITLE
给我个使用Pinus而不用pomelo的理由

### ISSUE THREAD

**Issue by NextZeus** [node-pinus/pinus#33]
本人是非常想学习了解新的服务器端的框架的，不过看到这个框架，有好多Pomelo的影子，所以忍不住想问几句: 

1. 开发者说是基于Pomelo的TS版本，还修改了一些bug和优化的地方， 请问能否详细列出来，否则我们不敢用(毕竟修改bug的过程中，也会有几率制造出新的bug)
2. 说实话，看着pinus说是pinus, 里面还有pomelo的用法，感觉有些许的别扭，就像是没有断了奶的孩子，还在使用父母的东西。让人感觉 这就是个TS语言改过来的Pomelo. 好感没有太多
3. 不知其他人是否有其他意见

**Comment by whtiehack** [comment]
就是pomelo的 TS版本。 协议都是一模一样的。  至于用pinus而不用 pomelo的理由，可以转变成 ‘用TS而不用 JS的理由',  好了，兄弟，你可以去baidu or google 了。

**Comment by fallshuang** [comment]
这种也算 issue ？ issue是啥意思？   把这种傻逼问题删除吧，也不要回答这种问题。

**Comment by NextZeus** [comment]
@fallshuang 请说好文明些。
