### ISSUE TITLE
pinus1.6.1执行pinus stop -P6000报错，pinus1.4.14没问题

### ISSUE THREAD

**Issue by sss316** [node-pinus/pinus#388]
刚看群里讨论，linux上pinus1.6.1执行pinus stop -P6000报错，pinus1.4.14没问题。
验证了下，报错信息：
net.js:985
throw new ERR_INVALID_ARG_TYPE('options.port'...
希望尽快修复！

**Comment by cmcreborn** [comment]
补充一下我这边测试情况

正常：
OS: MacOS 11.6.1, 11.6.2, Ubuntu 18.04, Ubuntu 20.04, WIN 10
Pinus : 1.4.14
Node: v16.13.1

异常,可复现问题：
OS: Ubuntu 18.04, Ubuntu 20.04
Pinus : 1.6.1
Node: v16.13.1

使用相同examples里的websocket-chat project

PS 手边尚未测试 pinus 1.6.1 的OS为 MacOS 11.6.1, 11.6.2, WIN10, 有相同问题的伙伴们在帮补

**Comment by whtiehack** [comment]
好了.一起测试一下看看

**Comment by cmcreborn** [comment]
> 好了.一起测试一下看看

OS: MacOS 11.6.1, 11.6.2, Ubuntu 18.04, Ubuntu 20.04

**Comment by sss316** [comment]
测试没问题

**Comment by whtiehack** [comment]
commander这个 从3直接更新到8了. 应该是改动比较大. 我给它降回来了. 
不降回来就要改不少源码 .怕出bug被坑进去.  然后 @types/node 也要跟着降.   

具体代码就是
https://github.com/node-pinus/pinus/blob/master/packages/pinus/bin/commands/stop.ts#L21

这个commands里的文件都要改.

有大佬有空的话可以提交pr.
