### ISSUE TITLE
mac 新建项目 报错

### ISSUE THREAD

**Issue by fanyingmao** [node-pinus/pinus#41]
![image](https://user-images.githubusercontent.com/14085720/45016766-42da1800-b058-11e8-9ef6-1d31b54addec.png)

**Comment by fanyingmao** [comment]
解决办法，还有其它到命令也会，好想是window编码在mac下的问题
https://stackoverflow.com/questions/37724444/getting-node-r-no-such-file-or-directory-error-with-swagon-on-osx

**Comment by fanyingmao** [comment]
解决办法，还有其它到命令也会，好想是window编码在mac下的问题
https://stackoverflow.com/questions/37724444/getting-node-r-no-such-file-or-directory-error-with-swagon-on-osx

**Comment by whtiehack** [comment]
对。是windows编码问题。
