### ISSUE TITLE
新建项目，启动服务器，循环依赖警告

### ISSUE THREAD

**Issue by anhuishuqi** [node-pinus/pinus#454]
新建项目，启动服务器，出现循环依赖警告。web服务器连接不上。我先是使用的node1.6版本，又换成了1.4版本
![01](https://user-images.githubusercontent.com/4415955/162331189-66e1ba7b-5e96-40f4-aeb5-6d9870bc24bf.png)
![02](https://user-images.githubusercontent.com/4415955/162331223-50c82585-dbdd-407f-9f39-6a947c5a552a.png)

**Comment by whtiehack** [comment]
node v16 
version 1.6.3
 警告有. 能正常跑 是一个子依赖报的


web-server 也能跑 


你第二张图命令错了

`node  --trace-warnings app`

**Comment by whtiehack** [comment]
原因是 `cliff`依赖`winston`.  winston发出的警告.  这两个依赖都太老的. cliff用的地方过多. 修复起来比较耗时. 暂时没发现有什么影响. 有时间再搞吧

**Comment by whtiehack** [comment]
新版本已经有大佬解决了.
