### ISSUE TITLE
多connector类型

### ISSUE THREAD

**Issue by lineCode** [node-pinus/pinus#503]
能启动多个不同类型的connector吗，比如两个ws，两个tcp，

**Comment by whtiehack** [comment]
可以的。

**Comment by sekkit** [comment]
hybridconnector如何自定义tcp或者是ws

**Comment by whtiehack** [comment]
hybird 默认直接支持 tcp或者ws客户端。  一般用的都是ws客户端， tcp客户端需要自己改。两者的差别只是一个走ws 一个走纯tcp，协议都一样的。

![image](https://user-images.githubusercontent.com/12741016/174483101-28b8e2de-e939-457d-bb01-1dee9da07f78.png)
其它几种connector都在这里。
