### ISSUE TITLE
express 太新 express.bodyParser() 这样的写法不支持

### ISSUE THREAD

**Issue by Jamlee** [node-pinus/pinus#519]
https://github.com/node-pinus/pinus/blob/e839a031e16e13631afcba46827cebb338184113/examples/simple-example/web-server/package.json#L6

express 降级到 3.21.2 demo 就可以跑了：
```
"express": "3.21.2"
````

**Comment by whtiehack** [comment]
fixed https://github.com/node-pinus/pinus/commit/bdff8eb313f003cb4df52f44de47aa698fa57ff1
