### ISSUE TITLE
centOS pinus No such file or directory

### ISSUE THREAD

**Issue by nameLogen** [node-pinus/pinus#55]
[root@izm5e9mals2xsrd0w9trjtz node_modules]# pinus
: No such file or directory
![image](https://user-images.githubusercontent.com/23234230/50219608-c0892000-03ca-11e9-876f-15b9c2e8b00b.png)
who can tell me why? thank you

**Comment by nameLogen** [comment]
pomelo is same handler , pomelo is ok,but pinus is cannot anywhere

**Comment by nameLogen** [comment]
![image](https://user-images.githubusercontent.com/23234230/50219852-718fba80-03cb-11e9-8736-b90ff4773d73.png)

**Comment by nameLogen** [comment]
Yes, the latter problem is solved,the server is started. but use pinus command is yet show “No such file or directory”

**Comment by nameLogen** [comment]
how to change the development or production environment ?

**Comment by nameLogen** [comment]
pinus start [-e,--env <env>] [-d,--directory <code directory>]
             [-D,--daemon] 
because my pinus cmd is not valid

**Comment by whtiehack** [comment]
#48

**Comment by whtiehack** [comment]
try it .

**Comment by nameLogen** [comment]
not work

**Comment by whtiehack** [comment]
Can you describe your problem more clear?
