### ISSUE TITLE
插件扩展相关

### ISSUE THREAD

**Issue by Yyang100** [node-pinus/pinus#578]
![image](https://user-images.githubusercontent.com/16314915/199910918-c8584abd-0fa4-4e97-ac0f-1c9f4b3f5b1d.png)

增加插件的时候发现，event 并不能和component 一样拥有app

**Comment by whtiehack** [comment]
pinus 和 pomelo的插件加载机制的确不一样
看起来event的app只能自己通过 opts参数传进去了

**Comment by whtiehack** [comment]
https://github.com/node-pinus/pinus/wiki/pinus-%E4%BD%BF%E7%94%A8pomelo%E6%8F%92%E4%BB%B6
