### ISSUE TITLE
示例工程中运执行npm-install.bat报错怎么处理

### ISSUE THREAD

**Issue by zhaxun** [node-pinus/pinus#596]
> pinus-workspaces@0.0.1 preinstall
> node -e "if(process.env.npm_execpath.indexOf('yarn') === -1) throw new Error('请使用 Yarn 来代替 NPM 安装依赖，请看：https://yarnpkg.com/zh-Hans/docs/install')"

[eval]:1
if(process.env.npm_execpath.indexOf('yarn') === -1) throw new Error('请使用 Yarn 来代替 NPM 安装依赖，请看：https://yarnpkg.com/zh-Hans/docs/install')
                                                    ^

Error: 请使用 Yarn 来代替 NPM 安装依赖，请看：https://yarnpkg.com/zh-Hans/docs/install
    at [eval]:1:59
    at Script.runInThisContext (node:vm:129:12)
    at Object.runInThisContext (node:vm:313:38)
    at node:internal/process/execution:79:19
    at [eval]-wrapper:6:22
    at evalScript (node:internal/process/execution:78:60)
    at node:internal/main/eval_string:28:3

Node.js v18.12.1
npm timing command:install Completed in 115047ms
npm ERR! code 1
npm ERR! path F:\GitHub\pinus
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node -e "if(process.env.npm_execpath.indexOf('yarn') === -1) throw new Error('请使用 Yarn 来代替 NPM 安装依赖，请看：https://yarnpkg.com/zh-Hans/docs/install')"
npm timing npm Completed in 115295ms

npm ERR! A complete log of this run can be found in:

**Comment by whtiehack** [comment]
把示例代码copy出来。不要直接在pinus的项目目录里。 项目目录里需要yarn。 copy出来就不需要了。

**Comment by zhaxun** [comment]
**copy到外部之后，game-server启动成功了**
**web-server启动失败，失败错误信息如下：**

> 
> PS F:\GitHub\simple-example\web-server> node app
> F:\GitHub\simple-example\web-server\node_modules\express\lib\express.js:112
>       throw new Error('Most middleware (like ' + name + ') is no longer bundled with Express and must be installed separately. Please see https://github.com/senchalabs/connect#middleware.');
>       ^
> 
> Error: Most middleware (like methodOverride) is no longer bundled with Express and must be installed separately. Please see https://github.com/senchalabs/connect#middleware.
>     at Function.get (F:\GitHub\simple-example\web-server\node_modules\express\lib\express.js:112:13)
>     at Object.<anonymous> (F:\GitHub\simple-example\web-server\app.js:4:19)
>     at Module._compile (node:internal/modules/cjs/loader:1159:14)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
>     at Module.load (node:internal/modules/cjs/loader:1037:32)
>     at Module._load (node:internal/modules/cjs/loader:878:12)
>     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
>     at node:internal/main/run_main_module:23:47
> 
> Node.js v18.12.1

**Comment by whtiehack** [comment]
web-server 只是个简单的http ，你个 public目录 运行 npx http-server 一样的效果
