### ISSUE TITLE
生命周期组建怎么使用

### ISSUE THREAD

**Issue by beiyouqgf** [node-pinus/pinus#61]
lifecycle 接口怎么使用，有没有例子

**Comment by whtiehack** [comment]
https://github.com/node-pinus/pinus/commit/c4ee2ecf8176a89527a0fcbb5a916228245b3f53

**Comment by beiyouqgf** [comment]
还想问一下啊 cancelShutDownTimer 这个方法的用途和使用方法

**Comment by whtiehack** [comment]
`pinus stop` 的时候，默认3秒后强制结束进程。   调用这个就是取消强制结束，把这个3秒的定时器清除掉。

**Comment by beiyouqgf** [comment]
嗯 好的 谢谢

**Comment by linguitang** [comment]
cancelShutDownTimer 没有生效吧，依然是3秒强制关服
![image](https://user-images.githubusercontent.com/8371546/56793009-87abfc80-683d-11e9-94d7-6e16b587cf95.png)

**Comment by whtiehack** [comment]
master进程与其它业务进程独立启动，不然master进程结束的时候 子进程也会被强制退出。

**Comment by linguitang** [comment]
> master进程与其它业务进程独立启动，不然master进程结束的时候 子进程也会被强制退出。

master如何独立启动？ @whtiehack 
除了简单粗暴的，单独一个master工程

**Comment by linguitang** [comment]
我在[https://github.com/node-pinus/pinus/issues/44](https://github.com/node-pinus/pinus/issues/44)找到了

**Comment by whtiehack** [comment]
我们是用 pm2控制所有进程的（wiki有更新相关的配置文件启动示例，可以参考一下）。
停服的逻辑是先阻断 connector,然后过几秒再停逻辑服。 通过给逻辑进程发送admin命令实现的。

可以参考一下。

**Comment by linguitang** [comment]
> 我们是用 pm2控制所有进程的[（wiki有更新相关的配置文件启动示例，可以参考一下）。](https://github.com/node-pinus/pinus/wiki/pinus%E9%85%8D%E7%BD%AE%E4%BD%BF%E7%94%A8pm2%E5%90%AF%E5%8A%A8%E5%B9%B6%E9%85%8D%E7%BD%AElog4js%E4%B8%8D%E5%86%99%E6%97%A5%E5%BF%97%E6%96%87%E4%BB%B6)
> 停服的逻辑是先阻断 connector,然后过几秒再停逻辑服。 通过给逻辑进程发送admin命令实现的。
> 
> 可以参考一下。

“通过给逻辑进程发送admin命令实现的”这个有参考吗？

**Comment by linguitang** [comment]
> 我们是用 pm2控制所有进程的[（wiki有更新相关的配置文件启动示例，可以参考一下）。](https://github.com/node-pinus/pinus/wiki/pinus%E9%85%8D%E7%BD%AE%E4%BD%BF%E7%94%A8pm2%E5%90%AF%E5%8A%A8%E5%B9%B6%E9%85%8D%E7%BD%AElog4js%E4%B8%8D%E5%86%99%E6%97%A5%E5%BF%97%E6%96%87%E4%BB%B6)
> 停服的逻辑是先阻断 connector,然后过几秒再停逻辑服。 通过给逻辑进程发送admin命令实现的。
> 
> 可以参考一下。

"通过给逻辑进程发送admin命令" 这个有参考吗？

**Comment by whtiehack** [comment]
> > 我们是用 pm2控制所有进程的[（wiki有更新相关的配置文件启动示例，可以参考一下）。](https://github.com/node-pinus/pinus/wiki/pinus%E9%85%8D%E7%BD%AE%E4%BD%BF%E7%94%A8pm2%E5%90%AF%E5%8A%A8%E5%B9%B6%E9%85%8D%E7%BD%AElog4js%E4%B8%8D%E5%86%99%E6%97%A5%E5%BF%97%E6%96%87%E4%BB%B6)
> > 停服的逻辑是先阻断 connector,然后过几秒再停逻辑服。 通过给逻辑进程发送admin命令实现的。
> > 可以参考一下。
> 
> "通过给逻辑进程发送admin命令" 这个有参考吗？单独使用pinus stop serverId不是关了后会自动重启么

自己写逻辑啊。 我只是说的我们是这样处理的。要看你自己的具体逻辑。
