### ISSUE TITLE
protobuf支持map吗？

### ISSUE THREAD

**Issue by ChaseRay1989** [node-pinus/pinus#612]

**Comment by whtiehack** [comment]
protobuf支持.  但是 `pomelo-protobuf` `pinus-protobuf` 不支持.

**Comment by ChaseRay520** [comment]
现在我们的项目有用到map的结构，这个如果要支持map结构，这个pinus-protobuf改动大吗

**Comment by ChaseRay520** [comment]
> protobuf支持. 但是 `pomelo-protobuf` `pinus-protobuf` 不支持.

现在我们的项目有用到map的结构，这个如果要支持map结构，这个pinus-protobuf改动大吗

**Comment by whtiehack** [comment]
> 这个如果要支持map结构，这个pinus-protobuf改动大吗

应该还好.毕竟也没多少代码.加个map类型的处理就好了. 客户端服务端都要改

**Comment by ChaseRay520** [comment]
> > 这个如果要支持map结构，这个pinus-protobuf改动大吗
> 
> 应该还好.毕竟也没多少代码.加个map类型的处理就好了. 客户端服务端

> whtiehack

这个map结构也算挺通用的，有没计划迭代新的版本支持这个功能？现在pinus还有在持续迭代优化吗？我看很久没更新了

**Comment by whtiehack** [comment]
现在只维护.

**Comment by ChaseRay1989** [comment]
> 现在只维护. 新功能你可以提交pr

提交了一个pr,在本地测了，map和object都可以，帮忙review一下看有没什么问题

**Comment by whtiehack** [comment]
https://github.com/node-pinus/pinus/pull/653

**Comment by ChaseRay1989** [comment]
p

> #653

pinus-protobuf是不是没有用字典压缩来减小字符串类型数据的大小？例如有重复的字符串，可以通过字典来代替，减少数据量

**Comment by ChaseRay1989** [comment]
> > 
> 
> 没有. 只用字典压缩了路由吧

这个不做为v1.6.6版本发布吗？我看到tag那里是单独一个命名发布
