### ISSUE TITLE
mqtt rpc client checkKeepAlive error timeout for 120000Error

### ISSUE THREAD

**Issue by Darkeril** [node-pinus/pinus#64]
稍微挂一会不连服务器就会出现这个情况，然后master会收到移除服务器的指令，这个怎么解决啊

**Comment by whtiehack** [comment]
描述的不太详细。

**Comment by Noly1990** [comment]
这个具体的原因没有找到，但是我分析了下，是服务器之间的rpc的mqtt的server和client之间的超时连接检测出了问题，详细的没有深究下去，但是我个人把mqtt的超时检测的默认时间从60秒改到40或者50秒以后这个问题就没有出现了，这个要改的话要去node_modules里去改的

**Comment by whtiehack** [comment]
如果是rpc问题。可以换用 tcp协议的rpc试试。

 出现这个情况的好像都是win10. 逻辑进程连master的问题。

**Comment by xiaowaGit** [comment]
这个问题我已经找到解决办法了，其实pomelo 在 linux 下偶尔也超时的，但是即使出现 timeout 之后 ，服务器还能正常运行。所以根本原因不是这个错误 ，而是这个错误 系统对待的方式，一个简单的timeout 怎么会把服务器搞崩嘛。win10 下面如果用cmd 运行 ，那么就肯定会崩，如果用PowerShell 运行 那么就不会崩了。亲测有效。

**Comment by Jason8Aaron** [comment]
这个什么情况。我以前node8.9.4基本不会。更高的版本会出现。现在8.9.4会出现。而且出现频率越发高了。

**Comment by kingForWorld** [comment]
[gate-server-1 mqttClient.js] mqtt rpc client checkKeepAlive error timeout for 120000Error:
环境:win7;
node:10.8.0
把服务挂在那里不动，经常会出现这种问题，不止这个gata服，connector也经常超时

**Comment by xiaowaGit** [comment]
win10&nbsp; 倒是经常这样 ，win7 我还没有出现过，如果你发布是在 linux 下 ，可以先不关心这个问题，发布就不会了，开发 忍忍




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"kingForWorld"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月26日(星期六) 下午4:48
收件人:&nbsp;"node-pinus/pinus"<pinus@noreply.github.com&gt;;
抄送:&nbsp;"小蛙"<598291606@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [node-pinus/pinus] mqtt rpc client checkKeepAlive error timeout for 120000Error (#64)




[gate-server-1 mqttClient.js] mqtt rpc client checkKeepAlive error timeout for 120000Error:
 环境:win7;
 node:10.8.0
 把服务挂在那里不动，经常会出现这种问题，不止这个gata服，connector也经常超时

**Comment by xiaowaGit** [comment]
Linux 下不会，建议用Windows子系统运行



发自我的iPhone


------------------ Original ------------------

**Comment by YunlongJiao-B** [comment]
默认的keepalive，10s 互相ping一次，超过20就timeout了
超时之后 emit close（此处应该重连才是）

**Comment by s8642795130** [comment]
这个问题已经找到了，提交了pr，麻烦review一下

**Comment by whtiehack** [comment]
#137  已经合并.
