### ISSUE TITLE
Handler继承后不能自动加入Route Dictionary

### ISSUE THREAD

**Issue by superyyl** [node-pinus/pinus#65]
### 基类 BaseHandler 

export default BaseHandler {
    protected app: Application;
    constructor(app: Application) {
        this.app = app;
    }
    async who(msg, session) {
        return {myname:this.constructor.name};
    }
}

### 子类 MyHandler

export default function(app) {return new MyHandler(app);}
export class MyHandler extends BaseHandler {
    constructor(app: Application) {
        super(app);
    }
    async myMethod(msg,session) {
        return {msg:'this is my method'};
    }
}

### 结果

启动时只过滤出了myMethod,who的方法没过滤出来

### 期望
myMethod和who都能过滤出来

**Comment by whtiehack** [comment]
![image](https://user-images.githubusercontent.com/12741016/53557815-b3826d00-3b81-11e9-9d6c-6b2f28d14259.png)
 是不是因为你没有new出来。你new出来试试。

**Comment by superyyl** [comment]
> ![image](https://user-images.githubusercontent.com/12741016/53557815-b3826d00-3b81-11e9-9d6c-6b2f28d14259.png)
> 是不是因为你没有new出来。你new出来试试。

Sorry, 我实际代码有写new, 贴上来时候漏了

export default function只有子类写了,基类只有在constructor里用super调用

**Comment by superyyl** [comment]
> ![image](https://user-images.githubusercontent.com/12741016/53557815-b3826d00-3b81-11e9-9d6c-6b2f28d14259.png)
> 是不是因为你没有new出来。你new出来试试。

我先看一下pinus-rpc/utils/utils.ts里的listEs6ClassMethods方法,应该是这个没把父类方法过滤出来

**Comment by superyyl** [comment]
`class BaseHandler {
    foo() {

    }
}

class MyHandler extends BaseHandler {
    bar() {

    }
}

function listEs6ClassMethods(objInstance: { [key: string]: any }) {
    if (objInstance.prototype && objInstance.prototype.constructor === objInstance) {
        let names: string[] = [];
        let methodNames = Object.getOwnPropertyNames(objInstance.prototype);
        for (let name of methodNames) {
            let method = objInstance.prototype[name];
            // Supposedly you'd like to skip constructor
            if (!(method instanceof Function) || name === 'constructor') continue;
            names.push(name);
        }
        return names;
    } else {
        let names: string[] = [];
        let methodNames = Object.getOwnPropertyNames(Object.getPrototypeOf(objInstance)).concat(Object.getOwnPropertyNames(objInstance));
        for (let name of methodNames) {
            let method = objInstance[name];
            // Supposedly you'd like to skip constructor
            if (!(method instanceof Function) || name === 'constructor') continue;
            names.push(name);
        }
        return names;
    }
}

let ret = listEs6ClassMethods(new MyHandler());

console.log(ret);`

print:[ 'bar' ]

**Comment by whtiehack** [comment]
> 文件 pinus/packages/pinus-rpc/lib/util/utils.ts
```
function listEs6ClassMethods(objInstance: { [key: string]: any }) {
    if (objInstance.prototype && objInstance.prototype.constructor === objInstance) {
        let names: string[] = [];
        let methodNames = Object.getOwnPropertyNames(objInstance.prototype);
        for (let name of methodNames) {
            let method = objInstance.prototype[name];
            // Supposedly you'd like to skip constructor
            if (!(method instanceof Function) || name === 'constructor') continue;
            names.push(name);
        }
        return names;
    } else {
        let names: string[] = [];
        let methodNames = Object.getOwnPropertyNames(Object.getPrototypeOf(objInstance)).concat(Object.getOwnPropertyNames(objInstance));
        for (let name of methodNames) {
            let method = objInstance[name];
            // Supposedly you'd like to skip constructor
            if (!(method instanceof Function) || name === 'constructor') continue;
            names.push(name);
        }
        return names;
    }
}

```



具体的代码是这个    现在有事不能研究了。


我测试了一下，的确不能获取到父类的方法。

```

class BaseHandler {
    protected app;
    constructor(app) {
        this.app = app;
    }
    public async who(msg, session) {
        return { myname: "this.constructor.name" };
    }
}


class MyHandler extends BaseHandler {
    constructor(app) {
        super(app);
    }
    public async myMethod(msg, session) {
        return { msg: 'this is my method' };
    }
}



console.log(listEs6ClassMethods(MyHandler))

let ins = new MyHandler(null)
console.log(listEs6ClassMethods(ins))
console.log(ins.who(null,null))
console.log(Object.getPrototypeOf(ins).constructor.prototype)
// 这一句才可以获取到父类的方法
console.log(Object.getPrototypeOf(ins.constructor.prototype))

```




你可以自己copy一下 dictionary组件 自己处理一下这个情况

用这名代码替换掉框架自带的 dictionary.
```
pinus.components.dictionary = DictionaryComponent;
```

**Comment by superyyl** [comment]
@whtiehack 感谢
