### ISSUE TITLE
请问下如何服务器和客户端之间的消息如何启用 compressGzip 进行压缩

### ISSUE THREAD

**Issue by anssser** [node-pinus/pinus#680]
请问下如何服务器和客户端之间的消息如何启用 compressGzip 进行压缩

**Comment by whtiehack** [comment]
没试过. 
帮你找到了原始的提交

https://github.com/NetEase/pomelo-protocol/commit/ceaedc5646815a7671b6e4b8e63fa305472e8880

**Comment by anssser** [comment]
> 没试过. 帮你找到了原始的提交
> 
> [NetEase/pomelo-protocol@ceaedc5](https://github.com/NetEase/pomelo-protocol/commit/ceaedc5646815a7671b6e4b8e63fa305472e8880)

好的, 非常感谢, 这个功能好像并没有完全实现.
还想请问下,服务器回给客户端的消息太大,有没有其他优雅的方式进行压缩.
