### ISSUE TITLE
在game-server目录下编译，却要进入dist进行运行，体验极差

### ISSUE THREAD

**Issue by zengmax** [node-pinus/pinus#7]

**Comment by mybios** [comment]
很好的建议，后面改成把config挪出来，启动时在game-server目录启动

**Comment by zengmax** [comment]
或者可以在game-server里面创建bat/sh文件一键编译、运行，也是一种方案

**Comment by mybios** [comment]
npm run start
就好，我们项目里就这么用的，在package.json里加个start的script就好。

**Comment by mybios** [comment]
已经增加npm run start的启动方式
