### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by cjpxyz** [node-pinus/pinus#71]
G:\projects\Library\pinus>npm install -g pinus --unsafe-perm
npm WARN deprecated circular-json@0.5.9: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated cryptiles@2.0.5: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated boom@2.10.1: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated hoek@2.16.3: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated socks@1.1.9: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
npm WARN deprecated mailcomposer@4.0.1: This project is unmaintained
npm WARN deprecated buildmail@4.0.1: This project is unmaintained
C:\Users\Administrator\AppData\Roaming\npm\pinus -> C:\Users\Administrator\AppData\Roaming\npm\node_modules\pinus\dist\bin\pinus.js
+ pinus@1.3.10
added 312 packages from 303 contributors in 63.66s
有这么多WARN deprecated这正常吗？

**Comment by whtiehack** [comment]
正常的。不影响。
