### ISSUE TITLE
客户端的下载链接都挂了，萌新刚开始学

### ISSUE THREAD

**Issue by IOXBruin** [node-pinus/pinus#72]
客户端的下载都挂了，萌新刚开始学。发现无法下载客户端接入的代码

**Comment by whtiehack** [comment]
用pomelo的客户端就行了。
另外 examples里有js 的客户端代码。 
源码里也有 ts版的 客户端代码。

**Comment by zhanghongjiandev** [comment]
> 用pomelo的客户端就行了。
> 另外 examples里有js 的客户端代码。
> 源码里也有 ts版的 客户端代码。

大佬，请问下，ts版的客户端代码具体在哪呢？ 现在客户端是ts项目，找不到需要的呢？前端是微信小游戏，也是用这个h5的websocket么？

**Comment by whtiehack** [comment]
> > 用pomelo的客户端就行了。
> > 另外 examples里有js 的客户端代码。
> > 源码里也有 ts版的 客户端代码。
> 
> 大佬，请问下，ts版的客户端代码具体在哪呢？ 现在客户端是ts项目，找不到需要的呢？前端是微信小游戏，也是用这个h5的websocket么？

https://github.com/node-pinus/pinus/blob/master/examples/robot-sample/app/script/PinusForEgret.ts
