### ISSUE TITLE
处理逻辑里的异步处理应该怎么做？

### ISSUE THREAD

**Issue by wushuning** [node-pinus/pinus#73]
handler里面的逻辑处理方法，没了像pomelo里面的next这样的设计，那如果设计到有各种数据库操作，或者需要进行redis锁操作等问题的话，怎么样才能延迟返回客户端数据？难道只能用回复一个空的数据，然后再推送一个别的消息的方式吗？萌新请教，谢谢指点

**Comment by whtiehack** [comment]
了解一下 async/await ,  Promise 相关的概念。
再回头来看 chat的示例你就明白了， pinus的handler和 remoter 是没有next的。 默认是Promise处理的。

handler remoter的接口执行完直接返回，就是类似默认自动调用 pomelo的next。

相关概念可以参考这里 : http://es6.ruanyifeng.com/
