### ISSUE TITLE
客户端发送的message为0或者空字符串，服务端解析出来为空对象，我用pomelo测试无问题

### ISSUE THREAD

**Issue by cn-qiuhong** [node-pinus/pinus#74]
如题

**Comment by whtiehack** [comment]
是不是配置了 protobuf. 检查下 protobuf配置。

**Comment by cn-qiuhong** [comment]
没有，pomelo有打印客户端发送的数据，传什么打印什么（body字段的值和客户端传的值是完全相等的），没问题，但是解析出来也是空的，pinus没有打印客户端发送的数据信息，解析出来也是空的，疑似所有假值在解析时被替换成了空对象。前端pomelo的代码中也有一句msg=msg||{},这样一想好像前后端处理方式一样，很合理。期间我试过把这句改成if(msg==null)msg={}，不改的话，发过去就是{}，改了以后pomelo打印的是对的，解析出来还是空对象。现在我把所有可能传假值的地方都包装成对象了。谢谢。
