### ISSUE TITLE
客户端build.js和服务器怎么感觉没有适配好？

### ISSUE THREAD

**Issue by bai1231111123** [node-pinus/pinus#745]
用npm下载的pinus，上面初始化出来的案例，启动了protobuf和dict，都没有效果，我进去翻了翻代码，感觉都没对上？这里git的里面的案例build.js又是一个版本?我把chat的案例里面build.js放到用pinus init的出来工程也对不上，数据都收不到? 现在还有在维护感觉有点乱？

**Comment by ptrjeffrey** [comment]
+1

**Comment by whtiehack** [comment]
初始化项目要选择 websockt 协议.其它协议都没有适配的客户端.  其它协议的客户端要自己去搬pomelo的.

**Comment by bai1231111123** [comment]
好像确实不完整解析里面,obj类型都没有。
