### ISSUE TITLE
could not find handle invalid data package

### ISSUE THREAD

**Issue by lwb051112** [node-pinus/pinus#75]
前端websocet通讯binaryType设置不了'arraybuffer',所以造成他发给服务端的数据是binary类型的"{\"@type\":\"binary\",\"base64\":\"AQAAS3sic3lzIjp7InR5cGUiOiJqcy13ZWJzb2NrZXQiLCJ2ZXJzaW9uIjoiMC4wLjEiLCJyc2EiOnt9LCJwcm90b1ZlcnNpb24iOjB9fQ==\",\"dataType\":\"ArrayBuffer\"}"

但是正确的它应该发Buffer类型 {"type":4,"body":{"type":"Buffer","data":[0,2,28,99,111,110,110,101,99,116,111,114,46,101,110,116,114,121,72,97,110,100,108,101,114,46,108,111,103,105,110,123,34,97,117,116,104,95,99,111,100,101,34,58,34,102,98,55,49,57,52,51,48,45,56,54,57,51,45,49,49,101,57,45,57,98,54,102,45,98,102,57,55,97,52,102,57,53,50,53,98,34,44,34,97,112,112,95,117,105,100,34,58,34,49,56,56,54,56,52,50,53,48,55,48,34,44,34,112,119,100,34,58,34,87,101,49,48,48,49,49,34,125]}}
导致它报：could not find handle invalid data package错误

虽然我在后端的hybridSocket.js文件的 socket.on('message'，..）方法里面对数据进行了转换，但是转换之后他不给前端返回数据了，而且servers的handler文件夹的处理方法也没走
1、我刚开始想是是不是common文件下的handler.js里面handleHandshake没走，最后看了是socket.state判断的时候导致了不对，所以直接没走了，但是不知道怎么改?

**Comment by lwb051112** [comment]
因为前端不能设置websocket的binaryType属性，binaryType属性默认值为Blob,导致后端接到的数据外层是Blob类型的数据。导致解析出错报:could not find handle invalid data package.

**Comment by whtiehack** [comment]
可能你需要把 connector 单独复制一份出来，配合你自己的客户端特性做修改。
