### ISSUE TITLE
examples有个示例是直接ts-run的，发现了一些问题，提醒大家谨慎使用

### ISSUE THREAD

**Issue by linguitang** [node-pinus/pinus#83]
一开始直接使用ts-run觉得挺爽的，因为不需要build一下再运行，后面使用sync模块的时候使用发现竟然不能同步，然后就跟着sync模块读了一遍代码，发现mapping.js里面的一段代码
![image](https://user-images.githubusercontent.com/8371546/61098077-44524900-a490-11e9-87b1-47567cfa9c0a.png)
这里面会判断是不是js文件，不是的话会直接返回，所以ts-run的话就没办法同步。
这里要么是改sync的代码，要么是还是换回build-run的方式，或者这块还是使用js，因为不知道还会不会有其他坑，所以保险一点还是直接使用build-run的方式

**Comment by whtiehack** [comment]
这个正常的吧。
理解了就行了。
另外 ts-run方式本来就是开发时用的。线上还是build方式稳妥。

而且你这个情况都找到原因了。可以通过hook方式解决掉，不用直接动模块本身。
require('pomelo-sync/lib/commands/mapping').loadMapping = xxxx

**Comment by linguitang** [comment]
> 这个正常的吧。
> 理解了就行了。
> 另外 ts-run方式本来就是开发时用的。线上还是build方式稳妥。
> 
> 而且你这个情况都找到原因了。可以通过hook方式解决掉，不用直接动模块本身。
> require('pomelo-sync/lib/commands/mapping').loadMapping = xxxx

嗯，通过这种方式改一下代码，做个兼容。线上是build方式好

**Comment by linguitang** [comment]
ts-run直接替换handler里面的文件也无法实现更新 @whtiehack

**Comment by whtiehack** [comment]
只是调试开发时候用的。。。。。
编译成 js以后不影响吧？

**Comment by linguitang** [comment]
@whtiehack 对，我只是列一下情况而已，js不影响的哈

**Comment by whtiehack** [comment]
嗯。。不影响就好。。。。不想去整这玩意了。只是开发调试方便就好了。。

**Comment by linguitang** [comment]
@whtiehack 发现还是有问题的，服务器刚开起来，没有客户端连接的时候，替换handler是可以实现更新，一旦有客户端连接后，替换handler就无效了。应该是客户端还没连接的时候，handler还没创建，一旦创建过了，就无法更新了。pinus/lib/common/service/handlerService.ts应该是没被执行到

**Comment by whtiehack** [comment]
![image](https://user-images.githubusercontent.com/12741016/62099428-941e7600-b2c0-11e9-9073-e385416f58aa.png)
没有复现你说的问题。

**Comment by whtiehack** [comment]
![image](https://user-images.githubusercontent.com/12741016/62099752-aa790180-b2c1-11e9-957e-8ccd216cc047.png)
remote的 热更新也没有发现问题。

可以把你的复现步骤描述一下吗？

**Comment by whtiehack** [comment]
另外我测试了一下 ts-run 的handler更新。也是没有问题的。

**Comment by linguitang** [comment]
我发现了一个奇怪的问题，我直接修改文件内容，是可以生效的，但是如果我把文件拷贝到另一个地方修改完再放回来，是不会生效的。你试试用文件替换的方式

**Comment by whtiehack** [comment]
https://github.com/nodejs/node/issues/22517

**Comment by whtiehack** [comment]
跟 inode有关系吧。可以参考一下。

**Comment by linguitang** [comment]
@whtiehack 请教一个问题,pinus-cli有没有办法用命令批量执行exec，比如有area1,area2,area3都需要exec同一个脚本，看文档只能一个个执行，有没有办法我写个脚本或者命令就全执行了

**Comment by linguitang** [comment]
> 跟 inode有关系吧。可以参考一下。

@whtiehack 这个确实是，Mac上有这种情况，centos上就没这种情况了

**Comment by whtiehack** [comment]
> @whtiehack 请教一个问题,pinus-cli有没有办法用命令批量执行exec，比如有area1,area2,area3都需要exec同一个脚本，看文档只能一个个执行，有没有办法我写个脚本或者命令就全执行了

忘记了，建议看一下对应命令的源码。看是不是可以直接命令执行而不进入交互。

**Comment by whtiehack** [comment]
这样感觉怎么样， 把 reload handler rmoter 功能抽出来，可以手动调用。 这样可控性感觉会更好。

**Comment by linguitang** [comment]
> 这样感觉怎么样， 把 reload handler rmoter 功能抽出来，可以手动调用。 这样可控性感觉会更好。

不是很明白。我自动更新 servers的文件是直接替换，项目的json利用fs.watch，也是直接替换就行了。其他ts文件是利用cli的exec，利用prototype特性进行重写

**Comment by whtiehack** [comment]
我的意思是 替换完 handler remoter以后， 类似这样调用 app.reloadHandler  app.reloadRemoter ，来手动重载。 而不是自动重载，这样也就不会有 inode问题了。

**Comment by whtiehack** [comment]
> 其他ts文件是利用cli的exec，利用prototype特性进行重写
你这里的意思是，你热更新自己逻辑的时候是通过 cli的run命令去 手动 require 然后 替换掉内存里现有对象的 prototype是吗？思路感觉不错的样子。

**Comment by linguitang** [comment]
> 我的意思是 替换完 handler remoter以后， 类似这样调用 app.reloadHandler app.reloadRemoter ，来手动重载。 而不是自动重载，这样也就不会有 inode问题了。

可以保留自动重载，直接替换文件就生效了，很方便。然后可以额外加个手动重载，有需要的话就自己调用

**Comment by linguitang** [comment]
> 其他ts文件是利用cli的exec，利用prototype特性进行重写
> 你这里的意思是，你热更新自己逻辑的时候是通过 cli的run命令去 手动 require 然后 替换掉内存里现有对象的 prototype是吗？思路感觉不错的样子。

对了，这样所有服务器代码就都可以热更新

**Comment by linguitang** [comment]
> 其他ts文件是利用cli的exec，利用prototype特性进行重写
> 你这里的意思是，你热更新自己逻辑的时候是通过 cli的run命令去 手动 require 然后 替换掉内存里现有对象的 prototype是吗？思路感觉不错的样子。

@whtiehack 我查看了文档，没有发现可以直接exec ts的方法，也没有发现可以批量 exec js的方法，如果服务器开很多个的话，要一直切换服务器进行exec也是麻烦

**Comment by whtiehack** [comment]
那就自己用 pinus-admin 写一个外接的命令。反正本身就有执行 scripts的 module了。

**Comment by linguitang** [comment]
> 那就自己用 pinus-admin 写一个外接的命令。反正本身就有执行 scripts的 module了。

不是很明白，可否详细一点

**Comment by whtiehack** [comment]
```
import {AdminClient} from 'pinus-admin';
export interface CommandArgs {
    action: string,
    args: any,
    servertype?: string,
    host?: string,
    port?: number,
    username?: string,
    password?: string
}

let parseArgs = function (args: string[]) {
    let argsMap: any = {};
    let mainPos = 1;

    while (args[mainPos].indexOf('--') > 0) {
        mainPos++;
    }
    argsMap.main = args[mainPos];

    for (let i = (mainPos + 1); i < args.length; i++) {
        let arg = args[i];
        let sep = arg.indexOf('=');
        let key = arg.slice(0, sep);
        let value = arg.slice(sep + 1);
        if (!isNaN(Number(value)) && (value.indexOf('.') < 0)) {
            value = Number(value) as any;
        }
        argsMap[key] = value;
    }

    return argsMap;
};
const program: CommandArgs = parseArgs(process.argv);


program.host = program.host ? program.host : '127.0.0.1';

program.port = program.port ? parseInt(program.port as any) : 3005;

program.username = program.username ? program.username : 'monitor';

program.password = program.password ? program.password : 'monitor';

if (!program.action) {
    console.error('paramgs error no action:', program);
    process.exit(1);
}
const client = new AdminClient({
    username: program.username,
    password: program.password,
    md5: true
});

let id = 'mycontrol_' + Date.now();
const resoveKeys = ['host', 'port', 'username', 'password'];

client.connect(id, program.host, program.port, (err: Error) => {
    if (err) {
        console.error('connector error:', err);
        process.exit(1);
    }
    let reqMsg = {};
    for (let k in program) {
        if (resoveKeys.includes(k)) {
            continue;
        }
        reqMsg[k] = program[k];
    }
    client.request('MyControlModule', reqMsg, (err, answer) => {
        if (err) {
            console.error('err:', err, 'answer:', answer);
            process.exit(-1);
        }
        console.log('answer:', JSON.stringify(answer, null, 4));
        process.exit(0);
    });
});

client.on('close', function () {
    client.socket.disconnect();
    console.error('\ndisconnect from master');
    process.exit(2);
});

```

这个是针对我自己的模块的。
可以参考一下。

你需要改成 script模块的调用吧

**Comment by linguitang** [comment]
@whtiehack 
![image](https://user-images.githubusercontent.com/8371546/62352638-3b0e4680-b53b-11e9-8445-5df382e6ad18.png)]
这个东西需要好多个参数，我目前已知的就serverId、command、script这些，好像还需要其他参数，可否给个示例？谢谢
