### ISSUE TITLE
npm start 编译报错  Property 'nodeId' is missing in type '{}'.

### ISSUE THREAD

**Issue by OTTOGH** [node-pinus/pinus#86]
node_modules/pinus-robot/lib/master/server.ts:107:33 - error TS2345: Argument of type '{}' is not assignable to parameter of type 'NodeClient'.
  Property 'nodeId' is missing in type '{}'.

107             web_client.add_node(node);
                                    ~~~~

**Comment by whtiehack** [comment]
已经修复了。  现在这个报错可以无视，实际已经编译好了。
不想无视的话就  npm uninstall @types/underscore    再 npm install @types/underscore@1.8.18

**Comment by OTTOGH** [comment]
ok

**Comment by whtiehack** [comment]
最新版本应该没有这个问题了。
