### ISSUE TITLE
jsclient-websocket, request的第128个请求得不到返回

### ISSUE THREAD

**Issue by skyblue** [node-pinus/pinus#865]
pinus.request@pinusnode-pinus-jsclient-websocket/lib/pinus-client.js

重现: 
连续发128个request, 第128个request得不到server端返回
 问题出在reqId的解析

<img width="662" alt="image" src="https://github.com/node-pinus/pinus/assets/248937/80e1506c-a22b-4c24-8489-728077f293bc">

**Comment by whtiehack** [comment]
你这个bug厉害了..
不带图也不带源码,直接说个结论.

![image](https://github.com/node-pinus/pinus/assets/12741016/86fc34b0-7905-49d9-b23c-ebdd61a8db1e)

我还专门写了个测试. 问题在哪呢?

**Comment by skyblue** [comment]
这个 issue 之前标 COMPLETED 但没看到关联修复 PR。我重新跑了一遍，确认 bug 仍存在并定位了根因，请维护者考虑重新打开。

## 根因

`packages/pinus-protocol/lib/protocol.ts` 里 `reqId` 的**服务端编/解码**用 **LSB-first**（低位在前，标准 protobuf varint），而 `pinus-jsclient-websocket` 客户端用的是 **MSB-first**（高位在前）。两者在 reqId < 128 时字节序差异被单字节路径掩盖，一旦 reqId ≥ 128 就会失配。

服务端相关代码：
- 编码 `encodeMsgId`（protocol.ts:290）：先写 `id % 128`（低位），再写 `Math.floor(id/128)`（高位）
- 解码（protocol.ts:200）：`id += (m & 0x7f) << (7 * i)`——把第 i 字节放在第 i*7 位

客户端代码（`packages/pinus/template/web-server/public/js/lib/build/build.js`，对应 `pinus-jsclient-websocket` 打包产物）：
- 编码：从末尾写 `id & 0x7f`（低位），向前写 `(id>>7) & 0x7f | 0x80`（高位+续位）
- 解码：`id = byte & 0x7f; while (byte & 0x80) { id <<= 7; byte = bytes[offset++]; id |= byte & 0x7f; }`

## 验证

我跑了一个跨端 round-trip 脚本，模拟客户端编码后用服务端解码：

| reqId | 客户端编码 | 服务端解码 | 预期 |
|---|---|---|---|
| 1–127 | `0xNN` | `NN` | ✓ |
| **128** | `[0x81, 0x00]` | **1** | 128 |
| 200 | `[0x81, 0x48]` | **9217** | 200 |
| 255 | `[0x81, 0x7f]` | **16257** | 255 |
| 256 | `[0x82, 0x00]` | **2** | 256 |

## 故障链

1. 第 128 次请求，客户端发 `id=128` → 字节 `[0x81, 0x00]`
2. 服务端按 LSB-first 解码得 `id=1`
3. 服务端处理后用 `id=1` 编码响应 → `[0x01]`
4. 客户端收到 `id=1`，去 `callbacks[1]` 找回调
5. `callbacks[1]` 早被第 1 次请求消耗并 delete
6. 第 128 次请求的回调（`callbacks[128]`）永远等不到响应

之所以"恰好第 128 个"：128 = 2^7，是首个需要 ≥ 2 字节 varint 的值，单字节路径下字节序差异不暴露。

## 修复方向

服务端必须改成 **MSB-first** 匹配客户端（客户端在另一个 npm 包里没法反向改）。具体改 `protocol.ts` 两处：

1. `encodeMsgId` 改用先算 `idBytes` + 末尾写低 7 位 / 向前写带续位的高位
2. 解码块改用 `id <<= 7; id |= byte & 0x7f` 模式

附回归测试覆盖 reqId = 1, 100, 127, 128, 129, 200, 255, 256, 16384。

## 风险

- 单字节路径（reqId < 128）字节流不变，对应客户端无影响
- 若有第三方自定义客户端走的是服务端 LSB-first 格式，会断——但它们 reqId ≥ 128 原本就坏，影响为零

## 计划

1. 先检查 `packages/pinus-rpc`（mqtt-acceptor 等路径）是否同病
2. 写回归测试，先复现 128→1 的失败
3. 修服务端，改完后 128→128
4. 单 PR 提交

不急，等维护者 review 这条根因分析后我再动代码。

**Comment by whtiehack** [comment]
@skyblue 修复了，我们用的客户端不一样，线上没用build.js所以一直没发现这个问题。
