### ISSUE TITLE
 app.rpcInvoke is not a function 

### ISSUE THREAD

**Issue by TimuJiang** [node-pinus/pinus#876]
在远程服务器上想对单独的用户发送一个通知
`	let tuid = msg.target + '*' + rid;
			let tsid = channel.getMember(tuid)['sid'];
			channelService.pushMessageByUids('onChat', param, [{
				uid: tuid,
				sid: tsid
			}]);`
app.rpcInvoke is not a function  报这个错误

**Comment by whtiehack** [comment]
可能服务没有启动成功. 或者你所在的服务器是错误的.
