### ISSUE TITLE
启动不了，报错  (`node:stream/web`)

### ISSUE THREAD

**Issue by qq564139153** [node-pinus/pinus#881]
![image](https://github.com/node-pinus/pinus/assets/7359614/1e4db26c-af0d-41f3-ac3f-eea7a8453c67)

**Comment by qq564139153** [comment]
![image](https://github.com/node-pinus/pinus/assets/7359614/24cbdb4f-1de4-44d9-89b3-f050add1aff3)

**Comment by qq564139153** [comment]
![image](https://github.com/node-pinus/pinus/assets/7359614/d2f06ab9-ade0-4876-8c5e-2dabe2a437d1)

**Comment by whtiehack** [comment]
`npm install` 以后 
再执行一次  `npm i engine.io-parser@5.2.1` 
5.2.2版本有问题.

**Comment by qq564139153** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
