### ISSUE TITLE
快速入门有些操作会报错，不知nodejs版本要求多少 10.x,14.x,20.x都试过

### ISSUE THREAD

**Issue by chanayy123** [node-pinus/pinus#882]
在game-server里npm install后执行npm run build会报一下错误：
node_modules/engine.io-parser/build/esm/index.d.ts:5:38 - error TS2307: Cannot find module 'node:stream/web' or its corresponding type declarations.

5 import type { TransformStream } from "node:stream/web";
                                       ~~~~~~~~~~~~~~~~~


Found 1 error in node_modules/engine.io-parser/build/esm/index.d.ts:5

**Comment by whtiehack** [comment]
没见过你这种错误.
10 14 20 都可以的吧.

你这个是不是npm install 没有 完全执行成功?

**Comment by whtiehack** [comment]
@chanayy123 

`npm install` 以后 
再执行一次  `npm i engine.io-parser@5.2.1` 
5.2.2版本有问题.

**Comment by chanayy123** [comment]
多谢多谢，真的是因为这个！
