### ISSUE TITLE
内存溢出 使用 --max-old-space-size=4096 还是没有解决问题

### ISSUE THREAD

**Issue by beiyouqgf** [node-pinus/pinus#90]
<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 000000A2635C9E51 <JS Object>
    1: fromString(aka fromString) [buffer.js:194] [pc=000003378855E0D0] (this=000000A263504189 <undefined>,string=00000099AE54CE31 <Very long string[1
96464212]>,encoding=000000A2635D6359 <String[4]: utf8>)
    2: from [buffer.js:94] [pc=000003378855DCF6] (this=000002E9C08A5BB1 <JS Function Buffer (SharedFunctionInfo 000000A2635E3899)>,value=00000099AE54C
E31 <Very long string[196464212]>,encod...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

pinus 应该怎么修改node默认的内存上线呢

**Comment by whtiehack** [comment]
你的程序什么逻辑？默认内存都不够你用？

node自身参数加在 config/server.json   args里面，如果要添加多个node参数 就用数组。

**Comment by beiyouqgf** [comment]
"hall": [
      {
        "id": "hall-server-1",
        "host": "127.0.0.1",
        "port": 3369,
        "args": "--max-old-space-size=4096"
      }
    ]
这样吗？

**Comment by beiyouqgf** [comment]
我设置了
然后打印了 memoryUsage
{ rss: 106606592,
  heapTotal: 87855104,
  heapUsed: 62746944,
  external: 18990429 }
还是没有增加
