### ISSUE TITLE
pinus init初始化的项目编译报错

### ISSUE THREAD

**Issue by zhanghongjiandev** [node-pinus/pinus#92]
报错在preload.ts中,
源码:
 process.on('unhandledRejection', (reason, p) => {
        console.error('Caught Unhandled Rejection at:' + p + 'reason:' + reason.stack);
    });
我能直接给reason指定类型reason: Error就能解决，但是每次初始化项目都必需改一次这么麻烦么？ 出错根本原因是哪里的版本问题么？

报错日志: 
Property 'stack' does not exist on type '{}'.

console.error('Caught Unhandled Rejection at:' + p + 'reason:' + reason.stack);

**Comment by whtiehack** [comment]
ts版本太高了。换2.9.2应该就好了。

**Comment by whtiehack** [comment]
3.5.2 应该也可以。

**Comment by whtiehack** [comment]
https://stackoverflow.com/questions/57331779/typescript-duplicate-identifier-iteratorresult

应该就是版本问题。 先退一下版本解决。

**Comment by whtiehack** [comment]
已经可以使用最新版的 ts了。
