### ISSUE TITLE
tsc自动编译问题

### ISSUE THREAD

**Issue by zero935** [node-pinus/pinus#95]
在centos7.5上自动编译报错
![Screenshot from 2019-11-05 10-06-02](https://user-images.githubusercontent.com/57379409/68172982-6e39f900-ffb4-11e9-916b-7c161fcfe2f7.png)
![Screenshot from 2019-11-05 10-06-47](https://user-images.githubusercontent.com/57379409/68172992-72fead00-ffb4-11e9-89e8-3d939bbb22ec.png)

**Comment by whtiehack** [comment]
ts版本换2.9.x 或者 3.5.x
