### ISSUE TITLE
生成的npm-install.sh具有目录跳转错误。

### ISSUE THREAD

**Issue by ShilongLee** [node-pinus/pinus#956]
<img width="542" alt="image" src="https://github.com/user-attachments/assets/9c6234ba-6a22-4cfd-889c-9a447d37cf7c">

**Comment by whtiehack** [comment]
应该是windows的  \r符号 。 你可以提交个pr 在 template 那个目录里好像

**Comment by ShilongLee** [comment]
好的，我发现原文件没有，应该是我手动弄错了。
