### ISSUE TITLE
关于(msg: any)的消息类型提示

### ISSUE THREAD

**Issue by ShilongLee** [node-pinus/pinus#960]
```typescript
export class Handler {
    constructor(private app: Application) {}

    async sendCode(msg: any, session: FrontendSession) {
        return {"code": 0, "msg": "ok", "data": {"hah": 1}};
    }
}
```
如果想要msg有类型提示的话，需要自己手写一个interface，既然proto已经表明过了消息结构，有没有办法通过clientProto.json自动生成参数提示。
如果有现成解决方案的话可以指一条明路吗，没有的话我写一个。

**Comment by whtiehack** [comment]
有从interface生成 proto.json的
https://github.com/whtiehack/pinus-parse-interface
