### ISSUE TITLE
这个dictionary配置里 协议和消息里序列化的cmd号绑定。方便业务向下兼容。

### ISSUE THREAD

**Issue by zerowise** [node-pinus/pinus#990]
这个dictionary配置逻辑是 把里面的配置按照字典顺序排序 作为消息里序列化的cmd号 ，这里在中间穿插新协议，会影响其他的协议的cmd号，业务上就无法做到向下兼容。不知道我理解的对不对。

我现在想到的方案配置变成这样
dictionary.json
```json
{
 "chat.chatHandler.send":1,
    "connector.entryHandler.enter":1000,
    "connector.entryHandler.onUserLeave":1001,
    "gate.gateHandler.queryEntry":2000
}
```
现在计划拉下代码自己改一遍。作者能不能提供对外接口，自己实现一套？

**Comment by whtiehack** [comment]
![image](https://github.com/user-attachments/assets/9fa00d60-a9b9-424b-898e-f2a02e76b054)

有个这个.可以替换自己的字典实现. 可以按你自己的需求修改.

**Comment by zerowise** [comment]
多谢。
